version: 1
accept_configuration:
  condition: property
  property: host.os
  equals_property: target.os

build_instructions:
  - !include "{{qt/qtbase}}/prepare_building_env.yaml"
  - !include "{{qt/qtbase}}/cmake_module_build_instructions.yaml"
  - !include "{{qt/qtbase}}/cmake_build_and_upload_test_artifacts.yaml"

test_instructions:
  - type: Group
    instructions:
      - !include "{{qt/qtbase}}/cmake_regular_test_instructions.yaml"
    disable_if:
      condition: property
      property: host.os
      equals_value: Windows
  - type: EnvironmentVariable
    variableName: Dummy
    variableValue: dummy
    enable_if:
      condition: property
      property: host.os
      equals_value: Windows
